
# Form implementation generated from reading ui file 'Q5.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (
    QWidget,
    QApplication,
    QTableWidgetItem,
    QVBoxLayout,
    QSpacerItem,
    QSizePolicy,
    QHBoxLayout,
    QSplitter,
)
import sys
from PyQt6.QtCore import Qt
from .T24 import HostControlPage as UI24
from .T25 import BatteryMonitor as UI25
from .T26 import BatteryMonitorBAL as UI26
from .T27 import BatteryMonitorTem as UI27
from .T28 import MainWindow as UI28
from  .T29 import Ui_Form as UI29
from  .T30 import  Ui_Form as UI30
from  .T31 import BatteryMonitorBAL as UI31
from .T32 import BalanceControlPage as UI32
from .T33 import HistoryLogPage as UI33
from .T34 import RealtimeMonitorPage as UI34
from .T35 import ActiveAlarmPage as UI35
from .T36 import DbcParsePage as UI36
from .T37 import CellVisualizationPage as UI37
from .T38 import SystemKLinePage as UI38
from .T39 import PowerDiagnosticPage as UI39
from .conf import config
from .responsive import FlowLayout

CU_NUM = config["BCU_NUM"]+2


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        available = QApplication.primaryScreen().availableGeometry()
        Form.resize(min(1600, available.width()), min(1000, available.height()))
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setObjectName("tabWidget")
        #self.tabWidget.setTextAlignment(Qt.AlignCenter)  # 设置内容居中




        self.tabWidget.setStyleSheet("""
                     QTabBar::tab {
                 width: 80px;  /* 控制每个tab的宽度 */
             }
             QTabBar::tab:selected {
                 font-weight: bold;  /* 选中的tab加粗 */
             }
             QTabWidget::tab-bar {
                 alignment: center;  /* 使tab居中对齐 */
             }
            QTableWidget {
                background-color: #f5f5f5;  /* 使用浅灰色背景，简洁清爽 */
                color: #333333;  /* 深灰色字体，简约且易读 */
                gridline-color: #e0e0e0;  /* 细浅的表格线，弱化但不失功能 */
                font-family: 'Segoe UI', 'Arial', sans-serif;  /* 现代、干净的字体 */
                font-size: 14px;  /* 适中的字体大小 */
                border: none;  /* 无边框，保持干净的外观 */
            }



            QTableWidget::item:selected {
                background-color: #d0f0ff;  /* 选中时使用柔和的蓝色背景，简洁但有质感 */
                color: #333333;  /* 保持深灰色字体颜色 */
            }

            QHeaderView::section {
                background-color: #eaeaea;  /* 表头使用稍深的灰色，突出但不刺眼 */
                color: #333333;  /* 表头字体为深灰色 */
                font-size: 12px;  /* 表头字体稍大一号 */
                font-weight: bold;  /* 表头加粗，突出重要性 */
                border: none;  /* 表头无边框，简洁 */
                padding: 10px;  /* 表头的内边距稍大，增加视觉舒适感 */
            }

            QScrollBar:vertical {
                background: #f5f5f5;
                width: 12px;
            }

            QScrollBar::handle:vertical {
                background: #cccccc;  /* 使用柔和的灰色滚动条 */
                border-radius: 6px;
            }

            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                background: #f5f5f5;
            }

            QTableCornerButton::section {
                background-color: #eaeaea;  /* 左上角的按钮背景与表头一致 */
            }
        """)

        self.tabWidget.setMinimumSize(0, 0)
        self.tabWidget.setMaximumSize(16777215, 16777215)
        self.tabWidget.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.tabBar().setExpanding(False)

        self.product_header = QtWidgets.QFrame(parent=Form)
        self.product_header.setObjectName("productHeader")
        self.product_header_layout = QHBoxLayout(self.product_header)
        self.product_header_layout.setContentsMargins(20, 8, 20, 8)
        self.product_header_layout.setSpacing(16)

        self.product_brand_block = QtWidgets.QWidget(parent=self.product_header)
        self.product_brand_block.setObjectName("productBrandBlock")
        self.product_brand_block.setMinimumWidth(190)
        self.product_brand_block.setMaximumWidth(220)
        self.product_brand_layout = QVBoxLayout(self.product_brand_block)
        self.product_brand_layout.setContentsMargins(0, 0, 0, 0)
        self.product_brand_layout.setSpacing(0)
        self.product_logo = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_logo.setObjectName("productLogo")
        self.product_logo.setText("AIDC")
        self.product_subtitle = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_subtitle.setObjectName("productSubtitle")
        self.product_subtitle.setText("AIDC CAN Host v" + str(config.get("Version", "")))
        self.product_context = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_context.setObjectName("productContext")
        self.product_context.setText("Project: AIDC    Profile: Test_4_10")
        self.product_brand_layout.addWidget(self.product_logo)
        self.product_brand_layout.addWidget(self.product_subtitle)
        self.product_brand_layout.addWidget(self.product_context)

        self.product_command_bar = QtWidgets.QFrame(parent=self.product_header)
        self.product_command_bar.setObjectName("productCommandBar")
        self.product_command_bar.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        self.product_command_stack = QVBoxLayout(self.product_command_bar)
        self.product_command_stack.setContentsMargins(0, 0, 0, 0)
        self.product_command_stack.setSpacing(6)

        self.product_bus_row = QtWidgets.QFrame(parent=self.product_command_bar)
        self.product_bus_row.setObjectName("productCommandRow")
        self.product_bus_layout = FlowLayout(
            self.product_bus_row,
            margin=0,
            horizontal_spacing=7,
            vertical_spacing=6,
        )
        self.product_action_row = QtWidgets.QFrame(parent=self.product_command_bar)
        self.product_action_row.setObjectName("productCommandRow")
        self.product_action_layout = FlowLayout(
            self.product_action_row,
            margin=0,
            horizontal_spacing=7,
            vertical_spacing=6,
        )
        self.product_command_stack.addWidget(self.product_bus_row)
        self.product_command_stack.addWidget(self.product_action_row)
        self.product_command_layout = self.product_bus_layout

        self.product_header_layout.addWidget(self.product_brand_block, 0, Qt.AlignmentFlag.AlignTop)
        self.product_header_layout.addWidget(self.product_command_bar, 1)

        # 创建水平和垂直布局
        v_layout = QVBoxLayout()
        v_layout.setContentsMargins(0, 0, 0, 0)
        v_layout.setSpacing(0)
        h_layout = QHBoxLayout()
        h_layout.setContentsMargins(0, 0, 0, 0)
        h_layout.setSpacing(0)

        # 添加水平伸缩空间，实现水平居中
        h_layout.addWidget(self.tabWidget)

        # 添加垂直伸缩空间，实现垂直居中
        v_layout.addWidget(self.product_header)
        v_layout.addLayout(h_layout, 1)

        # 将布局设置到窗口
        Form.setLayout(v_layout)


        stylesheet = """




        """
        Form.setStyleSheet(stylesheet)


        self.tab = [QtWidgets.QWidget() for i in range(0,CU_NUM+14)]
        self.TW = [[QtWidgets.QTableWidget(parent=self.tab[i]) for i in range(0,CU_NUM)] for j in range(0,3)]
        self.TW = [list(row) for row in zip(*self.TW)]#转置
        self.label = [[QtWidgets.QLabel(parent=self.tab[i]) for i in range(0,CU_NUM)] for j in range(0,3)]
        self.label = [list(row) for row in zip(*self.label)]#转置
        self._hidden_di_page = QtWidgets.QWidget(Form)
        self._hidden_parameter_page = QtWidgets.QWidget(Form)
        self._hidden_di_page.hide()
        self._hidden_parameter_page.hide()
        self.S17 = UI24()
        self.S18 = UI25()
        self.S19 = UI26()
        self.S20 = UI27()
        self.S21 = UI28()
        self.S22 = UI29()
        self.S23 = UI30()
        self.S24 = UI31()
        self.S25 = UI32()
        self.S26 = UI33()
        self.S27 = UI34()
        self.S28 = UI35()
        self.S29 = UI36()
        self.S30 = UI37()
        self.S31 = UI38()
        self.S32 = UI39()

        layout = QVBoxLayout(self.tab[CU_NUM+4])
        layout.addWidget(self.S28)

        layout = QVBoxLayout(self.tab[CU_NUM+5])
        layout.addWidget(self.S27)

        layout = QVBoxLayout(self.tab[CU_NUM])
        layout.addWidget(self.S18)

        layout = QVBoxLayout(self.tab[CU_NUM+1])
        layout.addWidget(self.S19)

        layout = QVBoxLayout(self.tab[CU_NUM+2])
        layout.addWidget(self.S20)

        layout = QVBoxLayout(self.tab[CU_NUM+3])
        layout.addWidget(self.S21)

        self.S22.setupUi(self._hidden_di_page)

        self.S23.setupUi(self._hidden_parameter_page)

        layout = QVBoxLayout(self.tab[CU_NUM+6])
        layout.addWidget(self.S17)

        layout = QVBoxLayout(self.tab[CU_NUM+7])
        layout.addWidget(self.S24)

        layout = QVBoxLayout(self.tab[CU_NUM+8])
        layout.addWidget(self.S25)

        layout = QVBoxLayout(self.tab[CU_NUM+9])
        layout.addWidget(self.S26)

        layout = QVBoxLayout(self.tab[CU_NUM+10])
        layout.addWidget(self.S29)

        layout = QVBoxLayout(self.tab[CU_NUM+11])
        layout.addWidget(self.S30)

        layout = QVBoxLayout(self.tab[CU_NUM+12])
        layout.addWidget(self.S31)

        layout = QVBoxLayout(self.tab[CU_NUM+13])
        layout.addWidget(self.S32)



        self.cluster_section_groups = []
        self.cluster_section_splitters = []
        for i in range(0,CU_NUM):
            #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[i]),"簇"+str(i))
            tab_layout = QVBoxLayout(self.tab[i])
            tab_layout.setContentsMargins(12, 12, 12, 12)
            tab_layout.setSpacing(8)
            splitter = QSplitter(Qt.Orientation.Horizontal, self.tab[i])
            splitter.setChildrenCollapsible(False)
            splitter.setHandleWidth(8)
            tab_layout.addWidget(splitter)
            section_groups = []

            for j in range(0,3):
                group = QtWidgets.QGroupBox(self.tab[i])
                group_layout = QVBoxLayout(group)
                group_layout.setContentsMargins(8, 12, 8, 8)
                group_layout.setSpacing(6)

                self.TW[i][j].setObjectName("tableWidget")
                self.TW[i][j].setColumnCount(3)
                self.TW[i][j].setRowCount(100)
                self.TW[i][j].setHorizontalHeaderLabels(["信号","值","单位"])
                self.TW[i][j].setMinimumSize(0, 0)
                self.TW[i][j].horizontalHeader().setSectionResizeMode(
                    0, QtWidgets.QHeaderView.ResizeMode.Stretch
                )
                self.TW[i][j].horizontalHeader().setSectionResizeMode(
                    1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents
                )
                self.TW[i][j].horizontalHeader().setSectionResizeMode(
                    2, QtWidgets.QHeaderView.ResizeMode.Stretch
                )

                self.label[i][j].setObjectName("sectionTitle")
                self.label[i][j].setAlignment(Qt.AlignmentFlag.AlignCenter)
                self.label[i][j].setWordWrap(True)
                group_layout.addWidget(self.label[i][j])
                group_layout.addWidget(self.TW[i][j], 1)
                splitter.addWidget(group)
                splitter.setStretchFactor(j, 1)
                section_groups.append(group)
                if i<CU_NUM-1:
                    if(j==0):
                        if config["Has_N"]==1:
                            self.label[i][j].setText("上半簇信息")
                        else:
                            self.label[i][j].setText("整簇信息（无中线）")
                    if(j==1):
                        if config["Has_N"] == 1:
                            self.label[i][j].setText("下半簇信息")
                        else:
                            self.label[i][j].setText("null")
                    if(j==2):
                        if config["Has_N"] == 1:
                            self.label[i][j].setText("整簇信息")
                        else:
                            self.label[i][j].setText("整簇信息(无中线)")
            self.cluster_section_groups.append(section_groups)
            self.cluster_section_splitters.append(splitter)

        self.apply_neutral_mode_labels(config.get("Has_N", 0) == 1)

        for i in range(0,CU_NUM+14):
            self.tabWidget.addTab(self.tab[i], "")
        if hasattr(self.tabWidget.tabBar(), "setTabVisible"):
            self.tabWidget.tabBar().setTabVisible(0, False)
            for i in range(2, CU_NUM - 1):
                self.tabWidget.tabBar().setTabVisible(i, False)


        #self.retranslateUi(Form)


        self.tabWidget.setCurrentIndex(1)
        #QtCore.QMetaObject.connectSlotsByName(Form)

        #self.tabCT =

        #Form.setObjectName("Form")
        #Form.resize(1378, 848)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def apply_neutral_mode_labels(self, has_neutral=None):
        has_neutral = bool(config.get("Has_N", 0)) if has_neutral is None else bool(has_neutral)
        if not hasattr(self, "label"):
            return
        if has_neutral:
            titles = ("上半簇信息", "下半簇信息", "整簇信息")
        else:
            titles = ("整簇运行信息（无中线）", "未使用（无中线）", "整簇参数/统计（无中线）")
        for cluster_index in range(0, max(CU_NUM - 1, 0)):
            for section_index, title in enumerate(titles):
                try:
                    self.label[cluster_index][section_index].setText(title)
                except (IndexError, AttributeError):
                    continue

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("V_{}".format(config["Version"]), "V_{}".format(config["Version"])))
        #self.tableWidget[0].setItem(0,0,QTableWidgetItem("测试"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "簇1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "簇2"))
        if CU_NUM > 2:
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[1]), "簇")
        for i in range(2,CU_NUM-1):
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[i]),"簇"+str(i))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[0]), "00")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM-1]), "BAU")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM]), "单体电压")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+1]), "均衡")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+2]), "单体温度")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+3]), "告警参数")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+4]), "实时告警")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+5]), "实时监控")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+6]), "主机控制")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+7]), "电芯异常")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+8]), "均衡控制")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+9]), "历史日志")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+10]), "DBC解析")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+11]), "单体3D")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+12]), "总压电流K线")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+13]), "上下电诊断")
        #Form.setWindowTitle(_translate("Form", "Form"))





if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = QWidget()
    Ui_Form().setupUi(w)
    w.show()
    sys.exit(app.exec())
