
# Form implementation generated from reading ui file 'Q5.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QApplication,QTableWidgetItem,QVBoxLayout,QSpacerItem,QSizePolicy,QHBoxLayout
import sys
from PyQt6.QtCore import Qt
from .T24 import Ui_Form as UI24
from .T25 import BatteryMonitor as UI25
from .T26 import BatteryMonitorBAL as UI26
from .T27 import BatteryMonitorTem as UI27
from .T28 import MainWindow as UI28
from  .T29 import Ui_Form as UI29
from  .T30 import  Ui_Form as UI30
from  .T31 import BatteryMonitorBAL as UI31


import yaml
with open('./conf.yaml', 'r', encoding='utf-8') as file:
    config = yaml.safe_load(file)["Test_4_10"]
CU_NUM = config["BCU_NUM"]+2


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 1000)
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1000))
        self.tabWidget.setObjectName("tabWidget")
        #self.tabWidget.setTextAlignment(Qt.AlignCenter)  # 设置内容居中




        self.tabWidget.setStyleSheet("""
                     QTabBar::tab {
                 width: 80px;  /* 控制每个tab的宽度 */
             }
             QTabBar::tab:selected {
                 font-weight: bold;  /* 选中的tab加粗 */
             }
             QTabWidget::tab-bar {
                 alignment: center;  /* 使tab居中对齐 */
             }
            QTableWidget {
                background-color: #f5f5f5;  /* 使用浅灰色背景，简洁清爽 */
                color: #333333;  /* 深灰色字体，简约且易读 */
                gridline-color: #e0e0e0;  /* 细浅的表格线，弱化但不失功能 */
                font-family: 'Segoe UI', 'Arial', sans-serif;  /* 现代、干净的字体 */
                font-size: 14px;  /* 适中的字体大小 */
                border: none;  /* 无边框，保持干净的外观 */
            }



            QTableWidget::item:selected {
                background-color: #d0f0ff;  /* 选中时使用柔和的蓝色背景，简洁但有质感 */
                color: #333333;  /* 保持深灰色字体颜色 */
            }

            QHeaderView::section {
                background-color: #eaeaea;  /* 表头使用稍深的灰色，突出但不刺眼 */
                color: #333333;  /* 表头字体为深灰色 */
                font-size: 12px;  /* 表头字体稍大一号 */
                font-weight: bold;  /* 表头加粗，突出重要性 */
                border: none;  /* 表头无边框，简洁 */
                padding: 10px;  /* 表头的内边距稍大，增加视觉舒适感 */
            }

            QScrollBar:vertical {
                background: #f5f5f5;
                width: 12px;
            }

            QScrollBar::handle:vertical {
                background: #cccccc;  /* 使用柔和的灰色滚动条 */
                border-radius: 6px;
            }

            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                background: #f5f5f5;
            }

            QTableCornerButton::section {
                background-color: #eaeaea;  /* 左上角的按钮背景与表头一致 */
            }
        """)

        self.tabWidget.setMinimumSize(0, 0)
        self.tabWidget.setMaximumSize(16777215, 16777215)
        self.tabWidget.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.tabBar().setExpanding(False)

        self.product_header = QtWidgets.QFrame(parent=Form)
        self.product_header.setObjectName("productHeader")
        self.product_header_layout = QHBoxLayout(self.product_header)
        self.product_header_layout.setContentsMargins(24, 10, 24, 10)
        self.product_header_layout.setSpacing(18)

        self.product_brand_block = QtWidgets.QWidget(parent=self.product_header)
        self.product_brand_block.setObjectName("productBrandBlock")
        self.product_brand_layout = QVBoxLayout(self.product_brand_block)
        self.product_brand_layout.setContentsMargins(0, 0, 0, 0)
        self.product_brand_layout.setSpacing(2)
        self.product_logo = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_logo.setObjectName("productLogo")
        self.product_logo.setText("AIDC")
        self.product_subtitle = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_subtitle.setObjectName("productSubtitle")
        self.product_subtitle.setText("AIDC CAN Host v" + str(config.get("Version", "")))
        self.product_context = QtWidgets.QLabel(parent=self.product_brand_block)
        self.product_context.setObjectName("productContext")
        self.product_context.setText("Project: AIDC    Profile: Test_4_10")
        self.product_brand_layout.addWidget(self.product_logo)
        self.product_brand_layout.addWidget(self.product_subtitle)
        self.product_brand_layout.addWidget(self.product_context)

        self.product_command_bar = QtWidgets.QFrame(parent=self.product_header)
        self.product_command_bar.setObjectName("productCommandBar")
        self.product_command_layout = QHBoxLayout(self.product_command_bar)
        self.product_command_layout.setContentsMargins(0, 0, 0, 0)
        self.product_command_layout.setSpacing(8)

        self.product_header_layout.addWidget(self.product_brand_block, 0, Qt.AlignmentFlag.AlignVCenter)
        self.product_header_layout.addStretch(1)
        self.product_header_layout.addWidget(self.product_command_bar, 0, Qt.AlignmentFlag.AlignVCenter)

        # 创建水平和垂直布局
        v_layout = QVBoxLayout()
        v_layout.setContentsMargins(0, 0, 0, 0)
        v_layout.setSpacing(0)
        h_layout = QHBoxLayout()
        h_layout.setContentsMargins(0, 0, 0, 0)
        h_layout.setSpacing(0)

        # 添加水平伸缩空间，实现水平居中
        h_layout.addWidget(self.tabWidget)

        # 添加垂直伸缩空间，实现垂直居中
        v_layout.addWidget(self.product_header)
        v_layout.addLayout(h_layout, 1)

        # 将布局设置到窗口
        Form.setLayout(v_layout)


        stylesheet = """




        """
        self.setStyleSheet(stylesheet)


        self.tab = [QtWidgets.QWidget() for i in range(0,CU_NUM+8)]
        self.TW = [[QtWidgets.QTableWidget(parent=self.tab[i]) for i in range(0,CU_NUM)] for j in range(0,3)]
        self.TW = [list(row) for row in zip(*self.TW)]#转置
        self.label = [[QtWidgets.QLabel(parent=self.tab[i]) for i in range(0,CU_NUM)] for j in range(0,3)]
        self.label = [list(row) for row in zip(*self.label)]#转置
        self.S17 = UI24()
        self.S18 = UI25()
        self.S19 = UI26()
        self.S20 = UI27()
        self.S21 = UI28()
        self.S22 = UI29()
        self.S23 = UI30()
        self.S24 = UI31()

        self.S17.setupUi(self.tab[CU_NUM])

        layout = QVBoxLayout(self.tab[CU_NUM+1])
        layout.addWidget(self.S18)

        layout = QVBoxLayout(self.tab[CU_NUM+2])
        layout.addWidget(self.S19)

        layout = QVBoxLayout(self.tab[CU_NUM+3])
        layout.addWidget(self.S20)

        layout = QVBoxLayout(self.tab[CU_NUM+4])
        layout.addWidget(self.S21)

        self.S22.setupUi(self.tab[CU_NUM+5])

        self.S23.setupUi(self.tab[CU_NUM+6])

        layout = QVBoxLayout(self.tab[CU_NUM+7])
        layout.addWidget(self.S24)



        for i in range(0,CU_NUM):
            #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[i]),"簇"+str(i))



            for j in range(0,3):
                self.TW[i][j].setGeometry(QtCore.QRect(j*600, 50, 800, 1000))
                self.TW[i][j].setObjectName("tableWidget")
                self.TW[i][j].horizontalHeader().setDefaultSectionSize(180)
                self.TW[i][j].setColumnCount(3)
                self.TW[i][j].setRowCount(100)
                self.TW[i][j].setHorizontalHeaderLabels(["信号","值","单位"])

                self.label[i][j].setGeometry(QtCore.QRect(300+j*600, 30, 81, 16))
                if i<CU_NUM-1:
                    if(j==0):
                        if config["Has_N"]==1:
                            self.label[i][j].setText("上半簇信息")
                        else:
                            self.label[i][j].setText("整簇信息（无中线）")
                    if(j==1):
                        if config["Has_N"] == 1:
                            self.label[i][j].setText("下半簇信息")
                        else:
                            self.label[i][j].setText("null")
                    if(j==2):
                        if config["Has_N"] == 1:
                            self.label[i][j].setText("整簇信息")
                        else:
                            self.label[i][j].setText("整簇信息(无中线)")

        for i in range(0,CU_NUM+8):
            self.tabWidget.addTab(self.tab[i], "")


        #self.retranslateUi(Form)


        self.tabWidget.setCurrentIndex(0)
        #QtCore.QMetaObject.connectSlotsByName(Form)

        #self.tabCT =

        #Form.setObjectName("Form")
        #Form.resize(1378, 848)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("V_{}".format(config["Version"]), "V_{}".format(config["Version"])))
        #self.tableWidget[0].setItem(0,0,QTableWidgetItem("测试"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "簇1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "簇2"))
        for i in range(1,CU_NUM-1):
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[i]),"簇"+str(i))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[0]), "00")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM-1]), "BAU")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM]), "控制")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+1]), "单体电压")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+2]), "均衡")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+3]), "单体温度")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+4]), "告警")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+5]), "DI状态")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM+6]), "参数管理")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab[CU_NUM + 7]), "电芯异常")
        #Form.setWindowTitle(_translate("Form", "Form"))





if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = QWidget()
    Ui_Form().setupUi(w)
    w.show()
    sys.exit(app.exec())
